export const SIEMENS_GROUP_MAP = {
    // === C: Disjuntores, Seccionadores, TC ===
    C00: 'Disjuntor',
    C01: 'Disjuntor',
    C02: 'Disjuntor',
    C03: 'Transformador',
    C05: 'Disjuntor',
    C06: 'Disjuntor',
    C08: 'Disjuntor',
    C10: 'Disjuntor',
    C11: 'Instrumentação',
    C13: 'Transformador',
    C14: 'Disjuntor',
    C15: 'Disjuntor',
    C17: 'Disjuntor',
    C18: 'Disjuntor',
    C19: 'Disjuntor',
    // === C: Comando, Sinalização, Contatores, Relés ===
    C30: 'Comando',
    C32: 'Comando',
    C35: 'Sinalização',
    C36: 'PLC',
    C37: 'Acessório',
    C38: 'Contator',
    C39: 'Contator',
    C40: 'Contator',
    C41: 'Relé',
    C42: 'Relé',
    C43: 'Relé',
    C44: 'Relé',
    C45: 'Relé',
    C46: 'Disjuntor',
    C47: 'Disjuntor',
    C48: 'Comando',
    C49: 'Soft-Starter',
    // === C: Uso geral ===
    C51: 'Disjuntor',
    C55: 'Contator',
    C56: 'Contator',
    C57: 'Fonte',
    C59: 'Contator',
    C61: 'PLC',
    C62: 'Acessório',
    C63: 'Contator',
    C64: 'Comando',
    C65: 'Contator',
    C67: 'Contator',
    C72: 'Disjuntor',
    C74: 'Disjuntor',
    C80: 'Transformador',
    C81: 'Transformador',
    C83: 'Transformador',
    C89: 'Relé',
    C91: 'Relé',
    C94: 'Contator',
    C96: 'Contator',
    C97: 'PLC',
    C98: 'Acessório',
    C99: 'Relé',
    CA2: 'Contator',
    // === E: Material Elétrico ===
    E03: 'Software',
    EAA: 'Disjuntor',
    EAB: 'Disjuntor',
    EAC: 'Disjuntor',
    EAF: 'Disjuntor',
    EAG: 'Disjuntor',
    EAH: 'Disjuntor',
    EAJ: 'Disjuntor',
    EAK: 'Disjuntor',
    EAL: 'Disjuntor',
    EAM: 'Acessório',
    EAN: 'Disjuntor',
    EBA: 'Disjuntor',
    EBB: 'Disjuntor',
    EBC: 'Disjuntor',
    ECA: 'Disjuntor',
    ECB: 'Acessório',
    EDB: 'Disjuntor',
    EDD: 'Disjuntor',
    EDE: 'Disjuntor',
    EDF: 'Disjuntor',
    EDG: 'Disjuntor',
    EDH: 'Disjuntor',
    EDL: 'Disjuntor',
    EEA: 'Instrumentação',
    EEB: 'Instrumentação',
    EEC: 'Relé',
    EED: 'Relé',
    EEE: 'Relé',
    EEH: 'Relé',
    EEI: 'Relé',
    EEJ: 'Disjuntor',
    EFA: 'Disjuntor',
    EFB: 'Disjuntor',
    EGA: 'Disjuntor',
    ELA: 'Cabo',
    ELB: 'Acessório',
    EMD: 'Acessório',
    EMG: 'Acessório',
    EMI: 'Disjuntor',
    EMJ: 'Acessório',
    EML: 'Acessório',
    EMM: 'Acessório',
    EMZ: 'Acessório',
    EOA: 'Disjuntor',
    EOB: 'Disjuntor',
    EOC: 'Disjuntor',
    EOD: 'Disjuntor',
    EOF: 'Disjuntor',
    EOI: 'Disjuntor',
    EOJ: 'Disjuntor',
    // === A: Automação ===
    A03: 'PLC',
    A23: 'Software',
    A33: 'PLC',
    A34: 'Acessório',
    A41: 'PLC',
    A43: 'PLC',
    A58: 'PLC',
    // === B: Proteção ===
    B20: 'Relé',
    B21: 'Relé',
    // === G: Pesagem ===
    G15: 'Instrumentação',
    G16: 'Instrumentação',
    // === I: Inversores ===
    I02: 'Inversor',
    I03: 'Inversor',
    I04: 'Inversor',
    I07: 'Inversor',
    I10: 'Inversor',
    I12: 'Inversor',
    I15: 'Inversor',
    // === J: Instrumentação ===
    J02: 'Instrumentação',
    J04: 'Instrumentação',
    J06: 'Instrumentação',
    J13: 'Instrumentação',
    J14: 'Instrumentação',
    J16: 'Instrumentação',
    J18: 'Instrumentação',
    J20: 'Instrumentação',
    J71: 'Instrumentação',
    J76: 'Instrumentação',
    J77: 'Instrumentação',
    J78: 'Instrumentação',
    // === K: Servomotores / Motion ===
    K02: 'PLC',
    K10: 'PLC',
    K11: 'PLC',
    K20: 'Inversor',
    K21: 'Inversor',
    K24: 'Inversor',
    K25: 'Inversor',
    K26: 'Inversor',
    K29: 'Inversor',
    K30: 'Inversor',
    K31: 'Inversor',
    K32: 'Inversor',
    K33: 'Inversor',
    K34: 'Inversor',
    K36: 'Inversor',
    K37: 'PLC',
    K40: 'Inversor',
    K41: 'Software',
    K42: 'Inversor',
    K45: 'Acessório',
    K50: 'Inversor',
    K53: 'Inversor',
    K54: 'Inversor',
    K57: 'Inversor',
    K58: 'Inversor',
    K59: 'Inversor',
    K63: 'Instrumentação',
    K64: 'Inversor',
    K65: 'Instrumentação',
    K68: 'Software',
    // === Z: PLC, HMI, Racks, Fontes ===
    Z10: 'PLC',
    Z12: 'Instrumentação',
    Z13: 'PLC',
    Z14: 'PLC',
    Z15: 'PLC',
    Z16: 'PLC',
    Z17: 'PLC',
    Z18: 'PLC',
    Z19: 'PLC',
    Z22: 'PLC',
    Z24: 'Software',
    Z31: 'PLC',
    Z32: 'PLC',
    Z37: 'Software',
    Z38: 'PLC',
    Z50: 'Acessório',
    Z51: 'Acessório',
    Z70: 'Fonte',
    Z71: 'Fonte'
};

export function getSiemensCategory(grupo) {
    if (!grupo) return null;
    const key = grupo.toString().trim().toUpperCase();
    return SIEMENS_GROUP_MAP[key] || null;
}

export const GRUPO_MATERIAL_2_COLUMNS = [
    'Grupo de material 2',
    'Grupo material 2',
    'grupo de material 2',
    'GRUPO DE MATERIAL 2',
    'Grupo Material 2',
    'grupo_material_2',
    '__EMPTY_3'
];

export function detectGrupoColumn(headers) {
    if (!headers || headers.length === 0) return null;
    const lower = headers.map(h => String(h).toLowerCase().trim());
    for (const col of GRUPO_MATERIAL_2_COLUMNS) {
        const idx = lower.indexOf(col.toLowerCase());
        if (idx !== -1) return idx;
    }
    return null;
}
